### ISSUE TITLE
README + Documentation Updates

### ISSUE THREAD

**Issue by BradenM** [BradenM/micropy-cli#395]
**Is your feature request related to a problem? Please describe.**

README and documentation are very outdated.

**Describe the solution you'd like**

- [ ] Update to reflect support for micropython-stubber integrated as a stub repository: #304
- [ ] Detail how management of stubs / stub repos is handled.
- [ ] #379 
- [ ] Explain upydevice/rshell backends: #294
- [ ] Creating stubs for custom modules (pending #394)
- [ ] Updated API reference (via autogendocs w/ mkdocs)
- [ ] Move to mkdocs.
- [ ] #312
